//! Generate random JSON values that conform to a [JSON Schema](https://json-schema.org/).
//!
//! `noson` takes a JSON Schema represented as a [`serde_json::Value`] and
//! produces a random JSON value that validates against it. The caller supplies
//! the random number generator, making output reproducible when a seeded RNG is
//! used.
//!
//! # Example
//!
//! ```
//! use rand::SeedableRng;
//! use rand::rngs::StdRng;
//! use serde_json::json;
//!
//! let schema = json!({
//!     "type": "object",
//!     "properties": {
//!         "name": { "type": "string", "minLength": 1, "maxLength": 20 },
//!         "age":  { "type": "integer", "minimum": 0, "maximum": 120 }
//!     },
//!     "required": ["name", "age"]
//! });
//!
//! let mut rng = StdRng::seed_from_u64(42);
//! let value = noson::generate(&schema, &mut rng).unwrap();
//! assert!(value.get("name").unwrap().is_string());
//! assert!(value.get("age").unwrap().is_i64());
//! ```
//!
//! # Supported Schema Features
//!
//! - **Types**: `null`, `boolean`, `string`, `integer`, `number`, `object`,
//!   `array`
//! - **Type unions**: `"type": ["string", "null"]` (array form of `type`) — one
//!   type is picked uniformly, and sibling constraints apply to it
//! - **Constraints**: `minimum`/`maximum`,
//!   `exclusiveMinimum`/`exclusiveMaximum`, `minLength`/`maxLength`,
//!   `minItems`/`maxItems`
//! - **Multiples**: `multipleOf` — a random multiple within the bounds,
//!   erroring when the range contains none
//! - **Tuples**: `prefixItems` — the first slots are generated positionally
//!   from the prefix schemas, later slots from `items`; `items: false` caps the
//!   length at the tuple size. The generated count covers the full tuple
//!   whenever `minItems`/`maxItems` allow
//! - **Array uniqueness**: `uniqueItems` — collisions are retried a bounded
//!   number of times per slot; when the item space is exhausted the array is
//!   returned short (never below `minItems`), and an error is returned when
//!   `minItems` distinct items cannot be found
//! - **Array containment**: `contains`/`minContains` — `minContains` slots (one
//!   by default) are generated from the merge of `contains` and the schema the
//!   slot would otherwise use, so they satisfy `contains` by construction, and
//!   the generated length always leaves room for them. Slots past the
//!   `prefixItems` prefix are preferred; a `contains` that cannot be merged
//!   with any slot's own schema is reported as conflicting. `minContains: 0`
//!   waives the requirement
//! - **Object sizing**: `minProperties`/`maxProperties` — property selection is
//!   count-aware: all required properties plus a random number of optional ones
//!   within the allowed range. When the declared properties cannot reach
//!   `minProperties`, extra entries are synthesized: names come from a
//!   `patternProperties` regex, the `propertyNames` schema, or fall back to
//!   random strings; values come from the matching `patternProperties` schema
//!   or `additionalProperties` (when it is a schema)
//! - **Dependencies**: `dependentRequired` — required properties pull in their
//!   transitive dependents; selecting an optional property pulls in its missing
//!   dependents too, and candidates whose dependents cannot fit within
//!   `maxProperties` are skipped
//! - **Pattern**: `pattern` — a random string is generated from the regex.
//!   `pattern` takes precedence over `format`. Samples are redrawn until one
//!   also satisfies `minLength`/`maxLength`; when no sample fits after a
//!   bounded number of attempts, the constraints are reported as conflicting.
//!   Patterns the generator cannot handle (invalid regexes, classes matching
//!   nothing) silently fall back to unconstrained string generation, so the
//!   result may not satisfy the pattern.
//! - **Format**: `date-time`, `date`, `time`, `duration`, `uuid`, `email`,
//!   `uri`, `hostname`, `ipv4`, `ipv6`
//! - **Enum / Const**: `enum`, `const`
//! - **Composition**: `allOf`, `anyOf`, `oneOf` — combined conjunctively with
//!   sibling keywords: a random `anyOf`/`oneOf` branch is merged with the rest
//!   of the schema, retrying other branches on conflict
//! - **Conditionals**: `if`/`then`/`else` — the then branch is generated by
//!   forcing the `if` condition and merging `then`; the else branch by merging
//!   `else` plus a negation of `if` when one is derivable (`if` is a
//!   single-property `const`/`enum` discriminator whose complement can be taken
//!   from the property's declared `enum`). When both branches are viable one is
//!   picked at random; otherwise the then branch is preferred and the else
//!   branch serves as the fallback on conflict
//! - **References**: `$ref` resolved against `$defs` / `definitions`; sibling
//!   keywords are merged conjunctively (2020-12 semantics)
//! - **Boolean schemas**: `true` (any value) and `false` (error)
//!
//! # Not Supported
//!
//! The following JSON Schema features are **not** currently handled. Schemas
//! using them will either be silently ignored (the keyword has no effect on
//! generation) or, in the case of external `$ref`, return an error.
//!
//! - **String**: `contentEncoding`, `contentMediaType`
//! - **Object**: `unevaluatedProperties`; `patternProperties` and
//!   `propertyNames` are only consulted when synthesizing extra entries — they
//!   are not enforced on declared `properties`
//! - **Array**: `additionalItems`, `maxContains`, `unevaluatedItems`
//! - **Composition**: `not`
//! - **Dependencies**: `dependentSchemas`
//! - **References**: external `$ref` (http/file URIs), `$dynamicRef`, `$anchor`

mod error;
mod generate;
mod xeger;

pub use error::Error;
pub use generate::generate;

#[cfg(test)]
mod tests {
    use rand::SeedableRng;
    use rand::rngs::StdRng;
    use serde_json::Value;
    use serde_json::json;

    use crate::generate;

    fn seeded_rng() -> StdRng {
        StdRng::seed_from_u64(42)
    }

    fn generate_and_validate(schema: &Value) {
        let mut rng = seeded_rng();
        let result = generate(schema, &mut rng).expect("generation should succeed");
        assert!(
            jsonschema::is_valid(schema, &result),
            "generated value does not validate against schema.\nschema: {schema}\nvalue: {result}"
        );
    }

    fn generate_and_validate_n(schema: &Value, n: usize) {
        let mut rng = seeded_rng();
        for i in 0..n {
            let result = generate(schema, &mut rng).expect("generation should succeed");
            assert!(
                jsonschema::is_valid(schema, &result),
                "sample {i} does not validate.\nschema: {schema}\nvalue: {result}"
            );
        }
    }

    // ── Scalars ──

    #[test]
    fn test_null() {
        let schema = json!({"type": "null"});
        generate_and_validate(&schema);
    }

    #[test]
    fn test_boolean() {
        let schema = json!({"type": "boolean"});
        generate_and_validate_n(&schema, 20);
    }

    #[test]
    fn test_string_basic() {
        let schema = json!({"type": "string"});
        generate_and_validate(&schema);
    }

    #[test]
    fn test_string_min_max_length() {
        let schema = json!({"type": "string", "minLength": 5, "maxLength": 10});
        let mut rng = seeded_rng();
        for _ in 0..50 {
            let result = generate(&schema, &mut rng).unwrap();
            let s = result.as_str().unwrap();
            assert!(
                s.len() >= 5 && s.len() <= 10,
                "string length {} out of range [5, 10]: {s}",
                s.len()
            );
        }
        generate_and_validate_n(&schema, 50);
    }

    #[test]
    fn test_integer_basic() {
        let schema = json!({"type": "integer"});
        generate_and_validate(&schema);
    }

    #[test]
    fn test_integer_min_max() {
        let schema = json!({"type": "integer", "minimum": 10, "maximum": 20});
        let mut rng = seeded_rng();
        for _ in 0..50 {
            let result = generate(&schema, &mut rng).unwrap();
            let n = result.as_i64().unwrap();
            assert!((10..=20).contains(&n), "integer {n} out of range [10, 20]");
        }
        generate_and_validate_n(&schema, 50);
    }

    #[test]
    fn test_number_basic() {
        let schema = json!({"type": "number"});
        generate_and_validate(&schema);
    }

    #[test]
    fn test_number_min_max() {
        let schema = json!({"type": "number", "minimum": 1.5, "maximum": 3.5});
        let mut rng = seeded_rng();
        for _ in 0..50 {
            let result = generate(&schema, &mut rng).unwrap();
            let n = result.as_f64().unwrap();
            assert!(
                (1.5..=3.5).contains(&n),
                "number {n} out of range [1.5, 3.5]"
            );
        }
        generate_and_validate_n(&schema, 50);
    }

    #[test]
    fn test_integer_multiple_of() {
        let schema = json!({"type": "integer", "minimum": 0, "multipleOf": 25});
        generate_and_validate_n(&schema, 100);
    }

    #[test]
    fn test_integer_multiple_of_narrow_range() {
        let schema = json!({
            "type": "integer",
            "minimum": 7,
            "maximum": 30,
            "multipleOf": 10
        });
        let mut rng = seeded_rng();
        for _ in 0..50 {
            let result = generate(&schema, &mut rng).unwrap();
            let n = result.as_i64().unwrap();
            assert!([10, 20, 30].contains(&n), "expected a multiple of 10: {n}");
        }
        generate_and_validate_n(&schema, 50);
    }

    #[test]
    fn test_integer_multiple_of_fractional() {
        // Integers that are multiples of 2.5 are the multiples of 5.
        let schema = json!({"type": "integer", "minimum": 1, "maximum": 100, "multipleOf": 2.5});
        let mut rng = seeded_rng();
        for _ in 0..50 {
            let result = generate(&schema, &mut rng).unwrap();
            let n = result.as_i64().unwrap();
            assert_eq!(n % 5, 0, "expected a multiple of 5: {n}");
        }
        generate_and_validate_n(&schema, 50);
    }

    #[test]
    fn test_integer_multiple_of_empty_range_returns_error() {
        let schema = json!({
            "type": "integer",
            "minimum": 11,
            "maximum": 19,
            "multipleOf": 25
        });
        let mut rng = seeded_rng();
        let err = generate(&schema, &mut rng).unwrap_err();
        assert!(
            matches!(err, crate::Error::ConflictingConstraints { .. }),
            "expected ConflictingConstraints, got: {err}"
        );
    }

    #[test]
    fn test_integer_multiple_of_non_positive_returns_error() {
        let schema = json!({"type": "integer", "multipleOf": 0});
        let mut rng = seeded_rng();
        let err = generate(&schema, &mut rng).unwrap_err();
        assert!(
            matches!(err, crate::Error::InvalidSchema { .. }),
            "expected InvalidSchema, got: {err}"
        );
    }

    #[test]
    fn test_number_multiple_of() {
        let schema = json!({
            "type": "number",
            "minimum": 0,
            "maximum": 10,
            "multipleOf": 0.25
        });
        generate_and_validate_n(&schema, 100);
    }

    #[test]
    fn test_number_multiple_of_fp_awkward_step() {
        // 0.1 is not exactly representable; k*0.1 must still satisfy the
        // validator's multipleOf check.
        let schema = json!({
            "type": "number",
            "minimum": 0.05,
            "maximum": 0.95,
            "multipleOf": 0.1
        });
        generate_and_validate_n(&schema, 100);
    }

    #[test]
    fn test_number_multiple_of_exclusive_bounds() {
        // Only 1.0 and 1.5 remain once the exclusive bounds shave off 0.5
        // and 2.0.
        let schema = json!({
            "type": "number",
            "exclusiveMinimum": 0.5,
            "exclusiveMaximum": 2.0,
            "multipleOf": 0.5
        });
        let mut rng = seeded_rng();
        for _ in 0..50 {
            let result = generate(&schema, &mut rng).unwrap();
            let n = result.as_f64().unwrap();
            assert!(n == 1.0 || n == 1.5, "expected 1.0 or 1.5: {n}");
        }
        generate_and_validate_n(&schema, 50);
    }

    // ── Type unions ──

    #[test]
    fn test_type_array_integer_null() {
        let schema = json!({"type": ["integer", "null"], "minimum": 1, "maximum": 6});
        let mut rng = seeded_rng();
        let mut saw_integer = false;
        let mut saw_null = false;
        for _ in 0..200 {
            let result = generate(&schema, &mut rng).unwrap();
            match &result {
                Value::Null => saw_null = true,
                Value::Number(n) => {
                    let n = n.as_i64().unwrap();
                    assert!((1..=6).contains(&n), "integer {n} out of range [1, 6]");
                    saw_integer = true;
                }
                other => panic!("unexpected variant: {other}"),
            }
        }
        assert!(saw_integer, "type array never generated an integer");
        assert!(saw_null, "type array never generated null");
        generate_and_validate_n(&schema, 200);
    }

    #[test]
    fn test_type_array_single_entry() {
        let schema = json!({"type": ["string"], "minLength": 3, "maxLength": 5});
        let mut rng = seeded_rng();
        for _ in 0..50 {
            let result = generate(&schema, &mut rng).unwrap();
            let s = result.as_str().unwrap();
            assert!(
                s.len() >= 3 && s.len() <= 5,
                "string length {} out of range [3, 5]: {s}",
                s.len()
            );
        }
        generate_and_validate_n(&schema, 50);
    }

    #[test]
    fn test_type_array_empty_returns_error() {
        let schema = json!({"type": []});
        let mut rng = seeded_rng();
        let err = generate(&schema, &mut rng).unwrap_err();
        assert!(
            matches!(err, crate::Error::InvalidSchema { .. }),
            "expected InvalidSchema, got: {err}"
        );
    }

    #[test]
    fn test_type_array_non_string_entry_returns_error() {
        let schema = json!({"type": [42]});
        let mut rng = seeded_rng();
        let err = generate(&schema, &mut rng).unwrap_err();
        assert!(
            matches!(err, crate::Error::InvalidSchema { .. }),
            "expected InvalidSchema, got: {err}"
        );
    }

    #[test]
    fn test_type_array_unknown_type_returns_error() {
        let schema = json!({"type": ["frob"]});
        let mut rng = seeded_rng();
        let err = generate(&schema, &mut rng).unwrap_err();
        assert!(
            matches!(err, crate::Error::UnsupportedType { .. }),
            "expected UnsupportedType, got: {err}"
        );
    }

    // ── Enum / Const ──

    #[test]
    fn test_const() {
        let schema = json!({"const": 42});
        let mut rng = seeded_rng();
        let result = generate(&schema, &mut rng).unwrap();
        assert_eq!(result, json!(42));
        generate_and_validate(&schema);
    }

    #[test]
    fn test_const_string() {
        let schema = json!({"const": "hello"});
        let mut rng = seeded_rng();
        let result = generate(&schema, &mut rng).unwrap();
        assert_eq!(result, json!("hello"));
        generate_and_validate(&schema);
    }

    #[test]
    fn test_enum() {
        let schema = json!({"enum": [1, "two", true, null]});
        let variants: Vec<Value> = vec![json!(1), json!("two"), json!(true), json!(null)];
        let mut rng = seeded_rng();
        for _ in 0..100 {
            let result = generate(&schema, &mut rng).unwrap();
            assert!(
                variants.contains(&result),
                "enum result {result} not in variants"
            );
        }
        generate_and_validate_n(&schema, 100);
    }

    // ── Objects ──

    #[test]
    fn test_object_basic() {
        let schema = json!({
            "type": "object",
            "properties": {
                "name": {"type": "string"},
                "age": {"type": "integer"},
                "optional_field": {"type": "boolean"}
            },
            "required": ["name", "age"]
        });
        let mut rng = seeded_rng();
        for _ in 0..20 {
            let result = generate(&schema, &mut rng).unwrap();
            let obj = result.as_object().unwrap();
            assert!(obj.contains_key("name"), "missing required field 'name'");
            assert!(obj.contains_key("age"), "missing required field 'age'");
        }
        generate_and_validate_n(&schema, 20);
    }

    #[test]
    fn test_object_all_required() {
        let schema = json!({
            "type": "object",
            "properties": {
                "a": {"type": "string"},
                "b": {"type": "integer"},
                "c": {"type": "boolean"}
            },
            "required": ["a", "b", "c"]
        });
        let mut rng = seeded_rng();
        for _ in 0..20 {
            let result = generate(&schema, &mut rng).unwrap();
            let obj = result.as_object().unwrap();
            assert!(obj.contains_key("a"));
            assert!(obj.contains_key("b"));
            assert!(obj.contains_key("c"));
        }
        generate_and_validate_n(&schema, 20);
    }

    #[test]
    fn test_object_nested() {
        let schema = json!({
            "type": "object",
            "properties": {
                "address": {
                    "type": "object",
                    "properties": {
                        "street": {"type": "string"},
                        "city": {"type": "string"}
                    },
                    "required": ["street", "city"]
                }
            },
            "required": ["address"]
        });
        generate_and_validate_n(&schema, 20);
    }

    #[test]
    fn test_object_max_properties() {
        // Many optional properties and a low cap — selection must be
        // count-aware, not a coin flip per property.
        let schema = json!({
            "type": "object",
            "additionalProperties": false,
            "maxProperties": 3,
            "properties": {
                "a": {"type": "number"},
                "b": {"type": "number"},
                "c": {"type": "number"},
                "d": {"type": "number"},
                "e": {"type": "number"},
                "f": {"type": "number"},
                "g": {"type": "number"}
            }
        });
        generate_and_validate_n(&schema, 100);
    }

    #[test]
    fn test_object_min_properties_from_declared() {
        let schema = json!({
            "type": "object",
            "additionalProperties": false,
            "minProperties": 2,
            "properties": {
                "a": {"type": "string"},
                "b": {"type": "string"},
                "c": {"type": "string"}
            }
        });
        generate_and_validate_n(&schema, 100);
    }

    #[test]
    fn test_object_map_shaped_additional_properties() {
        // No declared properties — entries must be synthesized from the
        // additionalProperties schema to satisfy minProperties.
        let schema = json!({
            "type": "object",
            "additionalProperties": {"type": "number", "minimum": 0, "maximum": 1},
            "minProperties": 1,
            "maxProperties": 4
        });
        let mut rng = seeded_rng();
        for i in 0..100 {
            let result = generate(&schema, &mut rng).expect("generation should succeed");
            assert!(
                jsonschema::is_valid(&schema, &result),
                "sample {i} does not validate.\nvalue: {result}"
            );
            let len = result.as_object().unwrap().len();
            assert!((1..=4).contains(&len), "sample {i} has {len} properties");
        }
    }

    #[test]
    fn test_object_pattern_properties_names_min_properties() {
        // Synthesized names must come from the patternProperties regex —
        // additionalProperties: false rejects everything else.
        let schema = json!({
            "type": "object",
            "additionalProperties": false,
            "patternProperties": {
                "^[a-z]{2,20}$": {"type": "boolean"}
            },
            "minProperties": 2
        });
        generate_and_validate_n(&schema, 100);
    }

    #[test]
    fn test_object_property_names_min_properties() {
        let schema = json!({
            "type": "object",
            "additionalProperties": {"type": "string"},
            "propertyNames": {"pattern": "^[a-z]+$"},
            "minProperties": 1
        });
        generate_and_validate_n(&schema, 100);
    }

    #[test]
    fn test_object_without_min_properties_synthesizes_nothing() {
        // A map-shaped schema with no lower bound keeps its current
        // behavior: no entries are invented.
        let schema = json!({
            "type": "object",
            "additionalProperties": false,
            "patternProperties": {
                "^[a-z]+$": {"type": "string"}
            }
        });
        let mut rng = seeded_rng();
        for _ in 0..20 {
            let result = generate(&schema, &mut rng).unwrap();
            assert_eq!(result, json!({}));
        }
    }

    #[test]
    fn test_object_required_undeclared_property_is_generated() {
        let schema = json!({
            "type": "object",
            "required": ["mystery"]
        });
        let mut rng = seeded_rng();
        for _ in 0..20 {
            let result = generate(&schema, &mut rng).unwrap();
            assert!(
                result.as_object().unwrap().contains_key("mystery"),
                "required property missing: {result}"
            );
        }
    }

    #[test]
    fn test_object_max_properties_below_required_returns_error() {
        let schema = json!({
            "type": "object",
            "properties": {"a": {"type": "string"}, "b": {"type": "string"}},
            "required": ["a", "b"],
            "maxProperties": 1
        });
        let mut rng = seeded_rng();
        let err = generate(&schema, &mut rng).unwrap_err();
        assert!(
            matches!(err, crate::Error::ConflictingConstraints { .. }),
            "expected ConflictingConstraints, got: {err}"
        );
    }

    #[test]
    fn test_object_min_properties_unsatisfiable_returns_error() {
        let schema = json!({
            "type": "object",
            "additionalProperties": false,
            "minProperties": 1
        });
        let mut rng = seeded_rng();
        let err = generate(&schema, &mut rng).unwrap_err();
        assert!(
            matches!(err, crate::Error::ConflictingConstraints { .. }),
            "expected ConflictingConstraints, got: {err}"
        );
    }

    #[test]
    fn test_object_dependent_required() {
        let schema = json!({
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "start": {"type": "string", "format": "date-time"},
                "end": {"type": "string", "format": "date-time"}
            },
            "dependentRequired": {"end": ["start"]}
        });
        generate_and_validate_n(&schema, 200);
    }

    #[test]
    fn test_object_dependent_required_transitive() {
        let schema = json!({
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "a": {"type": "integer"},
                "b": {"type": "integer"},
                "c": {"type": "integer"}
            },
            "dependentRequired": {"a": ["b"], "b": ["c"]}
        });
        generate_and_validate_n(&schema, 200);
    }

    #[test]
    fn test_object_dependent_required_of_required_property() {
        let schema = json!({
            "type": "object",
            "properties": {
                "end": {"type": "string"},
                "start": {"type": "string"}
            },
            "required": ["end"],
            "dependentRequired": {"end": ["start"]}
        });
        let mut rng = seeded_rng();
        for _ in 0..50 {
            let result = generate(&schema, &mut rng).expect("generation should succeed");
            assert!(
                result.get("start").is_some(),
                "required `end` must pull in `start`, got: {result}"
            );
            assert!(jsonschema::is_valid(&schema, &result));
        }
    }

    #[test]
    fn test_object_dependent_required_skips_candidates_over_max_properties() {
        let schema = json!({
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "a": {"type": "integer"},
                "b": {"type": "integer"},
                "c": {"type": "integer"}
            },
            "dependentRequired": {"a": ["b", "c"]},
            "maxProperties": 2
        });
        generate_and_validate_n(&schema, 200);
    }

    #[test]
    fn test_object_dependent_required_undeclared_dependent() {
        let schema = json!({
            "type": "object",
            "properties": {
                "a": {"type": "integer"}
            },
            "required": ["a"],
            "dependentRequired": {"a": ["z"]}
        });
        generate_and_validate_n(&schema, 50);
    }

    #[test]
    fn test_object_dependent_required_exceeding_max_properties_returns_error() {
        let schema = json!({
            "type": "object",
            "properties": {
                "end": {"type": "string"},
                "start": {"type": "string"}
            },
            "required": ["end"],
            "dependentRequired": {"end": ["start"]},
            "maxProperties": 1
        });
        let mut rng = seeded_rng();
        let err = generate(&schema, &mut rng).unwrap_err();
        assert!(
            matches!(err, crate::Error::ConflictingConstraints { .. }),
            "expected ConflictingConstraints, got: {err}"
        );
    }

    #[test]
    fn test_object_dependent_required_forbidden_dependent_returns_error() {
        let schema = json!({
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "a": {"type": "integer"}
            },
            "required": ["a"],
            "dependentRequired": {"a": ["z"]}
        });
        let mut rng = seeded_rng();
        let err = generate(&schema, &mut rng).unwrap_err();
        assert!(
            matches!(err, crate::Error::ConflictingConstraints { .. }),
            "expected ConflictingConstraints, got: {err}"
        );
    }

    // ── Arrays ──

    #[test]
    fn test_array_basic() {
        let schema = json!({"type": "array", "items": {"type": "integer"}});
        generate_and_validate(&schema);
    }

    #[test]
    fn test_array_min_max_items() {
        let schema = json!({
            "type": "array",
            "items": {"type": "integer"},
            "minItems": 2,
            "maxItems": 5
        });
        let mut rng = seeded_rng();
        for _ in 0..50 {
            let result = generate(&schema, &mut rng).unwrap();
            let arr = result.as_array().unwrap();
            assert!(
                arr.len() >= 2 && arr.len() <= 5,
                "array length {} out of range [2, 5]",
                arr.len()
            );
        }
        generate_and_validate_n(&schema, 50);
    }

    #[test]
    fn test_array_of_objects() {
        let schema = json!({
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "id": {"type": "integer"},
                    "name": {"type": "string"}
                },
                "required": ["id", "name"]
            },
            "minItems": 1,
            "maxItems": 3
        });
        generate_and_validate_n(&schema, 20);
    }

    #[test]
    fn test_array_unique_items_enum() {
        let schema = json!({
            "type": "array",
            "items": {
                "type": "string",
                "enum": ["violence", "drugs", "suicide", "sexual-content", "spoilers"]
            },
            "minItems": 1,
            "uniqueItems": true
        });
        generate_and_validate_n(&schema, 100);
    }

    #[test]
    fn test_array_unique_items_settles_short_when_space_is_small() {
        // Only two distinct items exist; maxItems asks for up to five. The
        // array must come back short rather than duplicated, and minItems: 1
        // is always reachable.
        let schema = json!({
            "type": "array",
            "items": {"enum": ["a", "b"]},
            "minItems": 1,
            "maxItems": 5,
            "uniqueItems": true
        });
        let mut rng = seeded_rng();
        for i in 0..100 {
            let result = generate(&schema, &mut rng).expect("generation should succeed");
            assert!(
                jsonschema::is_valid(&schema, &result),
                "sample {i} does not validate.\nvalue: {result}"
            );
            assert!(result.as_array().unwrap().len() <= 2);
        }
    }

    #[test]
    fn test_array_unique_items_min_items_unreachable_returns_error() {
        let schema = json!({
            "type": "array",
            "items": {"enum": ["a", "b"]},
            "minItems": 3,
            "uniqueItems": true
        });
        let mut rng = seeded_rng();
        let err = generate(&schema, &mut rng).unwrap_err();
        assert!(
            matches!(err, crate::Error::ConflictingConstraints { .. }),
            "expected ConflictingConstraints, got: {err}"
        );
    }

    #[test]
    fn test_array_unique_items_const_returns_error() {
        let schema = json!({
            "type": "array",
            "items": {"const": 7},
            "minItems": 2,
            "uniqueItems": true
        });
        let mut rng = seeded_rng();
        let err = generate(&schema, &mut rng).unwrap_err();
        assert!(
            matches!(err, crate::Error::ConflictingConstraints { .. }),
            "expected ConflictingConstraints, got: {err}"
        );
    }

    #[test]
    fn test_array_unique_items_false_allows_duplicates() {
        let schema = json!({
            "type": "array",
            "items": {"const": 7},
            "minItems": 2,
            "maxItems": 2,
            "uniqueItems": false
        });
        let mut rng = seeded_rng();
        let result = generate(&schema, &mut rng).expect("generation should succeed");
        assert_eq!(result, json!([7, 7]));
    }

    #[test]
    fn test_array_prefix_items_tuple() {
        let schema = json!({
            "type": "array",
            "prefixItems": [
                {"type": "number", "minimum": -90, "maximum": 90},
                {"type": "number", "minimum": -180, "maximum": 180}
            ],
            "minItems": 2,
            "maxItems": 2
        });
        generate_and_validate_n(&schema, 100);
    }

    #[test]
    fn test_array_prefix_items_with_items_for_rest() {
        let schema = json!({
            "type": "array",
            "prefixItems": [{"type": "string"}, {"type": "boolean"}],
            "items": {"type": "integer", "minimum": 0},
            "minItems": 3,
            "maxItems": 6
        });
        generate_and_validate_n(&schema, 100);
    }

    #[test]
    fn test_array_prefix_items_without_bounds_covers_tuple() {
        let schema = json!({
            "type": "array",
            "prefixItems": [{"const": "lat"}, {"const": "lon"}]
        });
        let mut rng = seeded_rng();
        for _ in 0..50 {
            let result = generate(&schema, &mut rng).expect("generation should succeed");
            let items = result.as_array().expect("array");
            assert!(items.len() >= 2, "expected the full tuple, got: {result}");
            assert_eq!(items[0], json!("lat"));
            assert_eq!(items[1], json!("lon"));
            assert!(jsonschema::is_valid(&schema, &result));
        }
    }

    #[test]
    fn test_array_prefix_items_items_false_caps_length() {
        let schema = json!({
            "type": "array",
            "prefixItems": [{"type": "integer"}, {"type": "string"}],
            "items": false,
            "minItems": 1
        });
        let mut rng = seeded_rng();
        for _ in 0..50 {
            let result = generate(&schema, &mut rng).expect("generation should succeed");
            assert!(
                result.as_array().expect("array").len() <= 2,
                "items: false must cap the length at the tuple size, got: {result}"
            );
            assert!(jsonschema::is_valid(&schema, &result));
        }
    }

    #[test]
    fn test_array_prefix_items_items_false_min_items_unreachable_returns_error() {
        let schema = json!({
            "type": "array",
            "prefixItems": [{"type": "integer"}, {"type": "string"}],
            "items": false,
            "minItems": 3
        });
        let mut rng = seeded_rng();
        let err = generate(&schema, &mut rng).unwrap_err();
        assert!(
            matches!(err, crate::Error::ConflictingConstraints { .. }),
            "expected ConflictingConstraints, got: {err}"
        );
    }

    #[test]
    fn test_array_prefix_items_unique_items() {
        let schema = json!({
            "type": "array",
            "prefixItems": [{"enum": ["a", "b"]}],
            "items": {"type": "integer", "minimum": 0, "maximum": 1000},
            "uniqueItems": true,
            "minItems": 1,
            "maxItems": 4
        });
        generate_and_validate_n(&schema, 100);
    }

    // ── Array contains ──

    /// The `64-gallery` corpus shape: "at least one image must be marked as
    /// the cover", where the flag is an optional boolean on the item schema.
    #[test]
    fn test_array_contains_cover_flag() {
        let schema = json!({
            "type": "array",
            "minItems": 1,
            "items": {
                "type": "object",
                "properties": {
                    "url": {"type": "string"},
                    "alt": {"type": "string"},
                    "cover": {"type": "boolean"}
                },
                "required": ["url", "alt"]
            },
            "contains": {
                "type": "object",
                "properties": {"cover": {"const": true}},
                "required": ["cover"]
            }
        });
        generate_and_validate_n(&schema, 200);
    }

    /// The `72-gallery` corpus shape — the same schema without `minItems`, so
    /// the satisfying element is what forces the array to be non-empty.
    #[test]
    fn test_array_contains_without_min_items_is_non_empty() {
        let schema = json!({
            "type": "array",
            "items": {
                "type": "object",
                "properties": {"cover": {"type": "boolean"}}
            },
            "contains": {
                "type": "object",
                "properties": {"cover": {"const": true}},
                "required": ["cover"]
            }
        });
        let mut rng = seeded_rng();
        for i in 0..200 {
            let value = generate(&schema, &mut rng).expect("generation should succeed");
            let items = value.as_array().expect("should generate an array");
            assert!(
                items
                    .iter()
                    .any(|item| item.get("cover") == Some(&json!(true))),
                "sample {i} has no element satisfying contains: {value}"
            );
        }
    }

    #[test]
    fn test_array_contains_true_is_non_empty() {
        let schema = json!({"type": "array", "items": {"type": "string"}, "contains": true});
        let mut rng = seeded_rng();
        for _ in 0..50 {
            let value = generate(&schema, &mut rng).expect("generation should succeed");
            assert!(
                !value
                    .as_array()
                    .expect("should generate an array")
                    .is_empty(),
                "contains requires at least one element: {value}"
            );
        }
    }

    /// `minContains: 0` waives the requirement, so no slot is forced — the
    /// `const` the `contains` schema asks for never appears.
    #[test]
    fn test_array_min_contains_zero_forces_nothing() {
        let schema = json!({
            "type": "array",
            "items": {"type": "integer", "minimum": 0, "maximum": 5},
            "maxItems": 3,
            "contains": {"const": 99},
            "minContains": 0
        });
        let mut rng = seeded_rng();
        for _ in 0..100 {
            let value = generate(&schema, &mut rng).expect("generation should succeed");
            let items = value.as_array().expect("should generate an array");
            assert!(
                !items.contains(&json!(99)),
                "minContains: 0 should force nothing, got {value}"
            );
        }
    }

    #[test]
    fn test_array_min_contains_two() {
        let schema = json!({
            "type": "array",
            "items": {"type": "string"},
            "minItems": 1,
            "maxItems": 5,
            "contains": {"type": "string", "maxLength": 3},
            "minContains": 2
        });
        generate_and_validate_n(&schema, 200);
    }

    /// The `68-highlight_quotes` corpus shape: the conditional injects
    /// `contains` and `minContains` into the array schema, so the satisfying
    /// slots have to be honoured on the merged schema rather than the
    /// declared one.
    #[test]
    fn test_array_contains_from_if_then_corpus_highlight_quotes() {
        let schema = json!({
            "type": "array",
            "items": {"type": "string"},
            "minItems": 1,
            "maxItems": 5,
            "if": {"minItems": 3},
            "then": {
                "contains": {"type": "string", "maxLength": 79},
                "minContains": 2
            }
        });
        generate_and_validate_n(&schema, 200);
    }

    /// Without an explicit `maxItems`, the default length accommodates
    /// `minContains` instead of conflicting with it.
    #[test]
    fn test_array_min_contains_above_default_max_items() {
        let schema = json!({
            "type": "array",
            "items": {"type": "integer"},
            "contains": {"type": "integer", "minimum": 100, "maximum": 200},
            "minContains": 5
        });
        generate_and_validate_n(&schema, 100);
    }

    #[test]
    fn test_array_contains_satisfied_through_prefix_slot() {
        let schema = json!({
            "type": "array",
            "prefixItems": [{"type": "integer", "minimum": 0, "maximum": 10}],
            "items": false,
            "contains": {"type": "integer", "minimum": 5}
        });
        generate_and_validate_n(&schema, 100);
    }

    #[test]
    fn test_array_contains_with_unique_items() {
        let schema = json!({
            "type": "array",
            "items": {"type": "integer", "minimum": 0, "maximum": 100},
            "uniqueItems": true,
            "minItems": 3,
            "contains": {"type": "integer", "minimum": 90}
        });
        generate_and_validate_n(&schema, 200);
    }

    /// `contains` alone, with no `type` or `items`, still identifies the
    /// schema as an array.
    #[test]
    fn test_array_contains_without_type_or_items() {
        let schema = json!({"contains": {"const": "x"}});
        let mut rng = seeded_rng();
        for _ in 0..50 {
            let value = generate(&schema, &mut rng).expect("generation should succeed");
            let items = value.as_array().expect("should generate an array");
            assert!(items.contains(&json!("x")), "expected an \"x\" in {value}");
        }
    }

    #[test]
    fn test_array_min_contains_above_max_items_returns_error() {
        let schema = json!({
            "type": "array",
            "items": {"type": "string"},
            "maxItems": 1,
            "contains": {"type": "string"},
            "minContains": 3
        });
        let mut rng = seeded_rng();
        let err = generate(&schema, &mut rng).unwrap_err();
        assert!(
            matches!(err, crate::Error::ConflictingConstraints { .. }),
            "expected ConflictingConstraints, got: {err}"
        );
    }

    #[test]
    fn test_array_contains_disjoint_from_items_returns_error() {
        let schema = json!({
            "type": "array",
            "items": {"type": "string"},
            "contains": {"type": "number"}
        });
        let mut rng = seeded_rng();
        let err = generate(&schema, &mut rng).unwrap_err();
        assert!(
            matches!(err, crate::Error::ConflictingConstraints { .. }),
            "expected ConflictingConstraints, got: {err}"
        );
    }

    #[test]
    fn test_array_contains_with_items_false_and_no_prefix_returns_error() {
        let schema = json!({
            "type": "array",
            "items": false,
            "contains": {"type": "string"}
        });
        let mut rng = seeded_rng();
        let err = generate(&schema, &mut rng).unwrap_err();
        assert!(
            matches!(err, crate::Error::ConflictingConstraints { .. }),
            "expected ConflictingConstraints, got: {err}"
        );
    }

    // ── Composition ──

    #[test]
    fn test_any_of() {
        let schema = json!({"anyOf": [{"type": "string"}, {"type": "integer"}]});
        generate_and_validate_n(&schema, 50);
    }

    #[test]
    fn test_any_of_all_variants_generated() {
        let schema =
            json!({"anyOf": [{"type": "string"}, {"type": "integer"}, {"type": "boolean"}]});
        let mut rng = seeded_rng();
        let mut saw_string = false;
        let mut saw_integer = false;
        let mut saw_boolean = false;
        for _ in 0..200 {
            let result = generate(&schema, &mut rng).unwrap();
            match &result {
                Value::String(_) => saw_string = true,
                Value::Number(n) if n.is_i64() => saw_integer = true,
                Value::Bool(_) => saw_boolean = true,
                other => panic!("unexpected variant: {other}"),
            }
        }
        assert!(saw_string, "anyOf never generated a string variant");
        assert!(saw_integer, "anyOf never generated an integer variant");
        assert!(saw_boolean, "anyOf never generated a boolean variant");
    }

    #[test]
    fn test_enum_all_variants_generated() {
        let schema = json!({"enum": [1, "two", true, null]});
        let mut rng = seeded_rng();
        let mut seen = std::collections::HashSet::new();
        for _ in 0..200 {
            let result = generate(&schema, &mut rng).unwrap();
            seen.insert(result.to_string());
        }
        assert!(seen.contains("1"), "enum never generated 1");
        assert!(seen.contains("\"two\""), "enum never generated \"two\"");
        assert!(seen.contains("true"), "enum never generated true");
        assert!(seen.contains("null"), "enum never generated null");
    }

    #[test]
    fn test_one_of() {
        let schema = json!({"oneOf": [{"type": "string"}, {"type": "integer"}]});
        generate_and_validate_n(&schema, 50);
    }

    #[test]
    fn test_all_of() {
        let schema = json!({
            "allOf": [
                {
                    "type": "object",
                    "properties": {
                        "name": {"type": "string"}
                    },
                    "required": ["name"]
                },
                {
                    "type": "object",
                    "properties": {
                        "age": {"type": "integer"}
                    },
                    "required": ["age"]
                }
            ]
        });
        let mut rng = seeded_rng();
        for _ in 0..20 {
            let result = generate(&schema, &mut rng).unwrap();
            let obj = result.as_object().unwrap();
            assert!(obj.contains_key("name"));
            assert!(obj.contains_key("age"));
        }
        // Note: jsonschema validation with allOf works on the generated merged
        // result
    }

    #[test]
    fn test_all_of_merges_constraints() {
        let schema = json!({"allOf": [{"type": "integer", "minimum": 5}, {"maximum": 7}]});
        let mut rng = seeded_rng();
        for _ in 0..50 {
            let result = generate(&schema, &mut rng).unwrap();
            let n = result.as_i64().unwrap();
            assert!((5..=7).contains(&n), "integer {n} out of range [5, 7]");
        }
        generate_and_validate_n(&schema, 50);
    }

    #[test]
    fn test_all_of_with_sibling_keywords() {
        let schema = json!({
            "type": "object",
            "properties": {"a": {"type": "string"}},
            "required": ["a"],
            "allOf": [{
                "properties": {"b": {"type": "integer"}},
                "required": ["b"]
            }]
        });
        let mut rng = seeded_rng();
        for _ in 0..20 {
            let result = generate(&schema, &mut rng).unwrap();
            let obj = result.as_object().unwrap();
            assert!(obj.contains_key("a"), "sibling required ignored");
            assert!(obj.contains_key("b"), "allOf member required ignored");
        }
        generate_and_validate_n(&schema, 20);
    }

    #[test]
    fn test_all_of_with_type_array_member() {
        let schema = json!({
            "minimum": 1,
            "maximum": 3,
            "allOf": [{"type": ["integer", "null"]}, {"type": "integer"}]
        });
        let mut rng = seeded_rng();
        for _ in 0..50 {
            let result = generate(&schema, &mut rng).unwrap();
            let n = result.as_i64().unwrap();
            assert!((1..=3).contains(&n), "integer {n} out of range [1, 3]");
        }
        generate_and_validate_n(&schema, 50);
    }

    #[test]
    fn test_all_of_conflicting_types_returns_error() {
        let schema = json!({"allOf": [{"type": "string"}, {"type": "integer"}]});
        let mut rng = seeded_rng();
        let err = generate(&schema, &mut rng).unwrap_err();
        assert!(
            matches!(err, crate::Error::ConflictingConstraints { .. }),
            "expected ConflictingConstraints, got: {err}"
        );
    }

    #[test]
    fn test_all_of_conflicting_const_returns_error() {
        let schema = json!({"const": 1, "allOf": [{"const": 2}]});
        let mut rng = seeded_rng();
        let err = generate(&schema, &mut rng).unwrap_err();
        assert!(
            matches!(err, crate::Error::ConflictingConstraints { .. }),
            "expected ConflictingConstraints, got: {err}"
        );
    }

    #[test]
    fn test_all_of_enum_intersection() {
        let schema = json!({"enum": [1, 2, 3], "allOf": [{"enum": [2, 3, 4]}]});
        let mut rng = seeded_rng();
        for _ in 0..50 {
            let result = generate(&schema, &mut rng).unwrap();
            let n = result.as_i64().unwrap();
            assert!([2, 3].contains(&n), "enum intersection violated: {n}");
        }
        generate_and_validate_n(&schema, 50);
    }

    #[test]
    fn test_any_of_with_sibling_keywords() {
        let schema = json!({
            "type": "integer",
            "minimum": 10,
            "anyOf": [{"maximum": 12}, {"minimum": 11, "maximum": 15}]
        });
        let mut rng = seeded_rng();
        for _ in 0..100 {
            let result = generate(&schema, &mut rng).unwrap();
            let n = result.as_i64().unwrap();
            assert!((10..=15).contains(&n), "integer {n} out of range [10, 15]");
        }
        generate_and_validate_n(&schema, 100);
    }

    #[test]
    fn test_one_of_with_sibling_keywords() {
        // Discriminated union drafted as sibling keywords (corpus file
        // 40-push_message): the outer type/properties/required apply
        // conjunctively with the picked oneOf branch.
        let schema = json!({
            "type": "object",
            "properties": {
                "channel": {"type": "string", "enum": ["push", "sms"]},
                "text": {"type": "string"}
            },
            "required": ["channel", "text"],
            "oneOf": [
                {"properties": {"channel": {"const": "sms"}, "text": {"maxLength": 160}}},
                {"properties": {"channel": {"const": "push"}, "text": {"maxLength": 512}}}
            ]
        });
        let mut rng = seeded_rng();
        let mut saw_sms = false;
        let mut saw_push = false;
        for _ in 0..200 {
            let result = generate(&schema, &mut rng).unwrap();
            let obj = result.as_object().unwrap();
            assert!(obj.contains_key("text"), "sibling required ignored");
            match obj.get("channel").and_then(Value::as_str) {
                Some("sms") => saw_sms = true,
                Some("push") => saw_push = true,
                other => panic!("unexpected channel: {other:?}"),
            }
        }
        assert!(saw_sms, "oneOf never picked the sms branch");
        assert!(saw_push, "oneOf never picked the push branch");
        // is_valid also asserts the exactly-one semantics of oneOf.
        generate_and_validate_n(&schema, 200);
    }

    #[test]
    fn test_one_of_conflicting_branch_is_retried() {
        // The integer branch conflicts with the sibling type; generation
        // must fall back to the other branch instead of erroring.
        let schema = json!({
            "type": "string",
            "minLength": 2,
            "maxLength": 2,
            "oneOf": [{"type": "integer"}, {}]
        });
        let mut rng = seeded_rng();
        for _ in 0..50 {
            let result = generate(&schema, &mut rng).unwrap();
            let s = result.as_str().unwrap();
            assert_eq!(s.len(), 2, "string length should be 2: {s}");
        }
        generate_and_validate_n(&schema, 50);
    }

    #[test]
    fn test_nested_one_of() {
        let schema = json!({"oneOf": [{"oneOf": [{"const": "a"}, {"const": "b"}]}]});
        let mut rng = seeded_rng();
        let mut seen = std::collections::HashSet::new();
        for _ in 0..100 {
            let result = generate(&schema, &mut rng).unwrap();
            seen.insert(result.as_str().unwrap().to_string());
        }
        assert!(seen.contains("a"), "nested oneOf never generated \"a\"");
        assert!(seen.contains("b"), "nested oneOf never generated \"b\"");
        generate_and_validate_n(&schema, 100);
    }

    // ── if/then/else ──

    #[test]
    fn test_if_then_else_discriminator_both_branches() {
        // 17-push_message shape, sharpened: the branch constraints use
        // minLength, which unconstrained generation (1..=10 chars) violates,
        // so this fails unless the matching branch is actually applied.
        let schema = json!({
            "type": "object",
            "properties": {
                "channel": {"type": "string", "enum": ["push", "sms"]},
                "text": {"type": "string"}
            },
            "required": ["channel", "text"],
            "if": {"properties": {"channel": {"const": "sms"}}},
            "then": {"properties": {"text": {"minLength": 20}}},
            "else": {"properties": {"text": {"minLength": 30}}}
        });
        let mut rng = seeded_rng();
        let mut saw_sms = false;
        let mut saw_push = false;
        for _ in 0..200 {
            let result = generate(&schema, &mut rng).unwrap();
            let obj = result.as_object().unwrap();
            let text_len = obj["text"].as_str().unwrap().len();
            match obj["channel"].as_str() {
                Some("sms") => {
                    saw_sms = true;
                    assert!(text_len >= 20, "then branch minLength ignored: {text_len}");
                }
                Some("push") => {
                    saw_push = true;
                    assert!(text_len >= 30, "else branch minLength ignored: {text_len}");
                }
                other => panic!("unexpected channel: {other:?}"),
            }
        }
        assert!(saw_sms, "if/then/else never took the then branch");
        assert!(saw_push, "if/then/else never took the else branch");
        generate_and_validate_n(&schema, 200);
    }

    #[test]
    fn test_if_then_else_corpus_push_message() {
        // Corpus file 17-push_message verbatim: maxLength conditionals under
        // additionalProperties: false.
        let schema = json!({
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "channel": {"type": "string", "enum": ["push", "sms"]},
                "text": {"type": "string"}
            },
            "required": ["channel", "text"],
            "if": {"properties": {"channel": {"const": "sms"}}},
            "then": {"properties": {"text": {"maxLength": 160}}},
            "else": {"properties": {"text": {"maxLength": 512}}}
        });
        generate_and_validate_n(&schema, 200);
    }

    #[test]
    fn test_if_then_without_else() {
        let schema = json!({
            "type": "object",
            "properties": {
                "channel": {"type": "string", "enum": ["push", "sms"]},
                "text": {"type": "string"}
            },
            "required": ["channel", "text"],
            "if": {"properties": {"channel": {"const": "sms"}}},
            "then": {"properties": {"text": {"minLength": 20}}}
        });
        let mut rng = seeded_rng();
        let mut saw_sms = false;
        let mut saw_push = false;
        for _ in 0..200 {
            let result = generate(&schema, &mut rng).unwrap();
            let obj = result.as_object().unwrap();
            match obj["channel"].as_str() {
                Some("sms") => {
                    saw_sms = true;
                    let text_len = obj["text"].as_str().unwrap().len();
                    assert!(text_len >= 20, "then branch minLength ignored: {text_len}");
                }
                Some("push") => saw_push = true,
                other => panic!("unexpected channel: {other:?}"),
            }
        }
        assert!(saw_sms, "if/then never took the then branch");
        assert!(saw_push, "if/then never took the vacuous else branch");
        generate_and_validate_n(&schema, 200);
    }

    #[test]
    fn test_if_else_without_then() {
        // Satisfying the condition leaves the value unconstrained; failing
        // it applies else.
        let schema = json!({
            "type": "object",
            "properties": {
                "channel": {"type": "string", "enum": ["push", "sms"]},
                "text": {"type": "string"}
            },
            "required": ["channel", "text"],
            "if": {"properties": {"channel": {"const": "sms"}}},
            "else": {"properties": {"text": {"minLength": 20}}}
        });
        let mut rng = seeded_rng();
        let mut saw_sms = false;
        let mut saw_push = false;
        for _ in 0..200 {
            let result = generate(&schema, &mut rng).unwrap();
            let obj = result.as_object().unwrap();
            match obj["channel"].as_str() {
                Some("sms") => saw_sms = true,
                Some("push") => {
                    saw_push = true;
                    let text_len = obj["text"].as_str().unwrap().len();
                    assert!(text_len >= 20, "else branch minLength ignored: {text_len}");
                }
                other => panic!("unexpected channel: {other:?}"),
            }
        }
        assert!(saw_sms, "if/else never took the vacuous then branch");
        assert!(saw_push, "if/else never took the else branch");
        generate_and_validate_n(&schema, 200);
    }

    #[test]
    fn test_if_alone_is_inert() {
        // `if` without `then`/`else` asserts nothing.
        let schema = json!({"type": "integer", "maximum": 10, "if": {"minimum": 50}});
        generate_and_validate_n(&schema, 50);
    }

    #[test]
    fn test_then_else_without_if_are_ignored() {
        let schema = json!({
            "type": "string",
            "maxLength": 3,
            "then": {"minLength": 9},
            "else": {"minLength": 9}
        });
        let mut rng = seeded_rng();
        for _ in 0..50 {
            let result = generate(&schema, &mut rng).unwrap();
            let len = result.as_str().unwrap().len();
            assert!(len <= 3, "bare then/else affected generation: {len}");
        }
        generate_and_validate_n(&schema, 50);
    }

    #[test]
    fn test_if_true_always_takes_then() {
        let schema = json!({"if": true, "then": {"const": "yes"}, "else": {"const": "no"}});
        let mut rng = seeded_rng();
        for _ in 0..20 {
            let result = generate(&schema, &mut rng).unwrap();
            assert_eq!(result, json!("yes"));
        }
        generate_and_validate_n(&schema, 20);
    }

    #[test]
    fn test_if_false_always_takes_else() {
        let schema = json!({"if": false, "then": {"const": "yes"}, "else": {"const": "no"}});
        let mut rng = seeded_rng();
        for _ in 0..20 {
            let result = generate(&schema, &mut rng).unwrap();
            assert_eq!(result, json!("no"));
        }
        generate_and_validate_n(&schema, 20);
    }

    #[test]
    fn test_if_unsatisfiable_with_base_falls_back_to_else() {
        // The base pins the discriminator away from the `if` value, so the
        // then branch conflicts and generation must take the else branch.
        let schema = json!({
            "type": "object",
            "properties": {
                "channel": {"type": "string", "enum": ["push"]},
                "text": {"type": "string"}
            },
            "required": ["channel", "text"],
            "if": {"properties": {"channel": {"const": "sms"}}},
            "then": {"properties": {"text": {"minLength": 50}}},
            "else": {"properties": {"text": {"minLength": 20}}}
        });
        let mut rng = seeded_rng();
        for _ in 0..50 {
            let result = generate(&schema, &mut rng).unwrap();
            let obj = result.as_object().unwrap();
            assert_eq!(obj["channel"], json!("push"));
            let text_len = obj["text"].as_str().unwrap().len();
            assert!(text_len >= 20, "else branch minLength ignored: {text_len}");
        }
        generate_and_validate_n(&schema, 50);
    }

    #[test]
    fn test_then_false_falls_back_to_else() {
        // `then: false` makes the if branch impossible even though the
        // condition is not a recognizable discriminator.
        let schema = json!({
            "type": "integer",
            "minimum": 0,
            "maximum": 100,
            "if": {"minimum": 50},
            "then": false,
            "else": {"maximum": 49}
        });
        let mut rng = seeded_rng();
        for _ in 0..50 {
            let result = generate(&schema, &mut rng).unwrap();
            let n = result.as_i64().unwrap();
            assert!(n <= 49, "then: false branch was not avoided: {n}");
        }
        generate_and_validate_n(&schema, 50);
    }

    #[test]
    fn test_non_discriminator_if_forces_then_branch() {
        // A non-discriminator `if` has no derivable negation, so generation
        // forces the condition and applies `then`.
        let schema = json!({
            "type": "integer",
            "minimum": 0,
            "maximum": 100,
            "if": {"minimum": 50},
            "then": {"multipleOf": 10}
        });
        let mut rng = seeded_rng();
        for _ in 0..50 {
            let result = generate(&schema, &mut rng).unwrap();
            let n = result.as_i64().unwrap();
            assert!(
                n <= 49 || n % 10 == 0,
                "conditional multipleOf violated: {n}"
            );
        }
        generate_and_validate_n(&schema, 50);
    }

    #[test]
    fn test_conditional_inside_all_of_member() {
        // The trio inside an allOf member must survive the merge and be
        // applied, not copied verbatim and then ignored.
        let schema = json!({
            "type": "object",
            "properties": {
                "kind": {"type": "string", "enum": ["a", "b"]},
                "size": {"type": "integer", "minimum": 0, "maximum": 100}
            },
            "required": ["kind", "size"],
            "allOf": [{
                "if": {"properties": {"kind": {"const": "a"}}},
                "then": {"properties": {"size": {"minimum": 90}}},
                "else": {"properties": {"size": {"maximum": 10}}}
            }]
        });
        let mut rng = seeded_rng();
        let mut saw_a = false;
        let mut saw_b = false;
        for _ in 0..200 {
            let result = generate(&schema, &mut rng).unwrap();
            let obj = result.as_object().unwrap();
            let size = obj["size"].as_i64().unwrap();
            match obj["kind"].as_str() {
                Some("a") => {
                    saw_a = true;
                    assert!(size >= 90, "then branch minimum ignored: {size}");
                }
                Some("b") => {
                    saw_b = true;
                    assert!(size <= 10, "else branch maximum ignored: {size}");
                }
                other => panic!("unexpected kind: {other:?}"),
            }
        }
        assert!(saw_a, "allOf conditional never took the then branch");
        assert!(saw_b, "allOf conditional never took the else branch");
        generate_and_validate_n(&schema, 200);
    }

    #[test]
    fn test_two_conditionals_in_all_of() {
        // Two if/then members at one level are both in force — legal JSON
        // Schema that must not raise a spurious merge conflict.
        let schema = json!({
            "type": "object",
            "properties": {
                "a": {"type": "integer", "enum": [1, 2]},
                "b": {"type": "integer", "enum": [3, 4]}
            },
            "required": ["a", "b"],
            "allOf": [
                {
                    "if": {"properties": {"a": {"const": 1}}},
                    "then": {"properties": {"flag_a": {"const": true}}, "required": ["flag_a"]}
                },
                {
                    "if": {"properties": {"b": {"const": 3}}},
                    "then": {"properties": {"flag_b": {"const": true}}, "required": ["flag_b"]}
                }
            ]
        });
        let mut rng = seeded_rng();
        for _ in 0..200 {
            let result = generate(&schema, &mut rng).unwrap();
            let obj = result.as_object().unwrap();
            if obj["a"] == json!(1) {
                assert_eq!(
                    obj.get("flag_a"),
                    Some(&json!(true)),
                    "then of the first conditional ignored: {result}"
                );
            }
            if obj["b"] == json!(3) {
                assert_eq!(
                    obj.get("flag_b"),
                    Some(&json!(true)),
                    "then of the second conditional ignored: {result}"
                );
            }
        }
        generate_and_validate_n(&schema, 200);
    }

    #[test]
    fn test_nested_conditional_in_then() {
        let schema = json!({
            "type": "object",
            "properties": {
                "a": {"type": "string", "enum": ["x", "y"]},
                "b": {"type": "string", "enum": ["p", "q"]}
            },
            "required": ["a", "b"],
            "if": {"properties": {"a": {"const": "x"}}},
            "then": {
                "if": {"properties": {"b": {"const": "p"}}},
                "then": {"properties": {"c": {"const": 1}}, "required": ["c"]}
            }
        });
        let mut rng = seeded_rng();
        for _ in 0..200 {
            let result = generate(&schema, &mut rng).unwrap();
            let obj = result.as_object().unwrap();
            if obj["a"] == json!("x") && obj["b"] == json!("p") {
                assert_eq!(
                    obj.get("c"),
                    Some(&json!(1)),
                    "nested then ignored: {result}"
                );
            }
        }
        generate_and_validate_n(&schema, 200);
    }

    #[test]
    fn test_conditional_with_one_of_siblings() {
        // The trio combines conjunctively with sibling oneOf.
        let schema = json!({
            "type": "object",
            "properties": {
                "channel": {"type": "string", "enum": ["push", "sms"]},
                "text": {"type": "string"}
            },
            "required": ["channel", "text"],
            "oneOf": [
                {"properties": {"priority": {"const": "high"}}, "required": ["priority"]},
                {"properties": {"priority": {"const": "low"}}, "required": ["priority"]}
            ],
            "if": {"properties": {"channel": {"const": "sms"}}},
            "then": {"properties": {"text": {"minLength": 20}}}
        });
        let mut rng = seeded_rng();
        for _ in 0..100 {
            let result = generate(&schema, &mut rng).unwrap();
            let obj = result.as_object().unwrap();
            assert!(obj.contains_key("priority"), "oneOf required ignored");
            if obj["channel"] == json!("sms") {
                let text_len = obj["text"].as_str().unwrap().len();
                assert!(text_len >= 20, "then branch minLength ignored: {text_len}");
            }
        }
        generate_and_validate_n(&schema, 100);
    }

    #[test]
    fn test_all_of_const_outside_enum_returns_error() {
        let schema = json!({"enum": ["a", "b"], "allOf": [{"const": "c"}]});
        let mut rng = seeded_rng();
        let err = generate(&schema, &mut rng).unwrap_err();
        assert!(
            matches!(err, crate::Error::ConflictingConstraints { .. }),
            "expected ConflictingConstraints, got: {err}"
        );

        let schema = json!({"const": "c", "allOf": [{"enum": ["a", "b"]}]});
        let mut rng = seeded_rng();
        let err = generate(&schema, &mut rng).unwrap_err();
        assert!(
            matches!(err, crate::Error::ConflictingConstraints { .. }),
            "expected ConflictingConstraints, got: {err}"
        );
    }

    #[test]
    fn test_all_of_const_within_enum_merges() {
        let schema = json!({"enum": ["a", "b"], "allOf": [{"const": "a"}]});
        let mut rng = seeded_rng();
        for _ in 0..20 {
            let result = generate(&schema, &mut rng).unwrap();
            assert_eq!(result, json!("a"));
        }
        generate_and_validate_n(&schema, 20);
    }

    // ── $ref ──

    #[test]
    fn test_ref_basic() {
        let schema = json!({
            "$defs": {
                "Name": {"type": "string", "minLength": 1, "maxLength": 20}
            },
            "type": "object",
            "properties": {
                "name": {"$ref": "#/$defs/Name"}
            },
            "required": ["name"]
        });
        generate_and_validate_n(&schema, 20);
    }

    #[test]
    fn test_ref_not_found() {
        let schema = json!({
            "type": "object",
            "properties": {
                "name": {"$ref": "#/$defs/NonExistent"}
            },
            "required": ["name"]
        });
        let mut rng = seeded_rng();
        let result = generate(&schema, &mut rng);
        assert!(result.is_err());
    }

    #[test]
    fn test_ref_nested() {
        let schema = json!({
            "$defs": {
                "Address": {
                    "type": "object",
                    "properties": {
                        "street": {"type": "string"},
                        "city": {"type": "string"}
                    },
                    "required": ["street", "city"]
                }
            },
            "type": "object",
            "properties": {
                "home": {"$ref": "#/$defs/Address"},
                "work": {"$ref": "#/$defs/Address"}
            },
            "required": ["home"]
        });
        generate_and_validate_n(&schema, 20);
    }

    #[test]
    fn test_ref_resolves_to_correct_type() {
        // Verify that $ref actually produces values matching the referenced
        // definition, not just "any valid JSON".
        let schema = json!({
            "$defs": {
                "PositiveInt": {"type": "integer", "minimum": 1, "maximum": 1000}
            },
            "type": "object",
            "properties": {
                "count": {"$ref": "#/$defs/PositiveInt"}
            },
            "required": ["count"]
        });
        let mut rng = seeded_rng();
        for _ in 0..50 {
            let result = generate(&schema, &mut rng).unwrap();
            let count = result.get("count").expect("missing 'count'");
            let n = count.as_i64().expect("count should be integer");
            assert!(
                (1..=1000).contains(&n),
                "ref-resolved value {n} doesn't match PositiveInt constraints"
            );
        }
    }

    #[test]
    fn test_ref_definitions_legacy() {
        // "definitions" (draft-07 style) should work the same as "$defs"
        let schema = json!({
            "definitions": {
                "Color": {"type": "string", "enum": ["red", "green", "blue"]}
            },
            "type": "object",
            "properties": {
                "color": {"$ref": "#/definitions/Color"}
            },
            "required": ["color"]
        });
        let mut rng = seeded_rng();
        let result = generate(&schema, &mut rng).unwrap();
        let color = result.get("color").unwrap().as_str().unwrap();
        assert!(
            ["red", "green", "blue"].contains(&color),
            "unexpected color: {color}"
        );
        generate_and_validate_n(&schema, 20);
    }

    #[test]
    fn test_ref_with_sibling_keywords() {
        let schema = json!({
            "$defs": {
                "Base": {
                    "type": "object",
                    "properties": {"id": {"type": "integer"}},
                    "required": ["id"]
                }
            },
            "$ref": "#/$defs/Base",
            "properties": {"name": {"type": "string"}},
            "required": ["name"]
        });
        let mut rng = seeded_rng();
        for _ in 0..20 {
            let result = generate(&schema, &mut rng).unwrap();
            let obj = result.as_object().unwrap();
            assert!(obj.contains_key("id"), "$ref target required ignored");
            assert!(obj.contains_key("name"), "sibling required ignored");
        }
        generate_and_validate_n(&schema, 20);
    }

    #[test]
    fn test_ref_external_returns_error() {
        // External $ref (http/file URLs) are not supported and should
        // return a RefNotFound error rather than panicking.
        let schema = json!({
            "type": "object",
            "properties": {
                "item": {"$ref": "https://example.com/schemas/item.json"}
            },
            "required": ["item"]
        });
        let mut rng = seeded_rng();
        let result = generate(&schema, &mut rng);
        assert!(result.is_err(), "external $ref should return an error");
        let err = result.unwrap_err();
        assert!(
            matches!(err, crate::Error::RefNotFound { .. }),
            "expected RefNotFound, got: {err}"
        );
    }

    // ── Edge cases ──

    #[test]
    fn test_empty_object_schema() {
        let schema = json!({"type": "object"});
        let mut rng = seeded_rng();
        let result = generate(&schema, &mut rng).unwrap();
        assert!(result.is_object());
        generate_and_validate(&schema);
    }

    #[test]
    fn test_empty_array_schema() {
        let schema = json!({"type": "array"});
        let mut rng = seeded_rng();
        let result = generate(&schema, &mut rng).unwrap();
        assert!(result.is_array());
        generate_and_validate(&schema);
    }

    #[test]
    fn test_string_zero_length() {
        let schema = json!({"type": "string", "minLength": 0, "maxLength": 0});
        let mut rng = seeded_rng();
        let result = generate(&schema, &mut rng).unwrap();
        assert_eq!(result, json!(""));
        generate_and_validate(&schema);
    }

    #[test]
    fn test_integer_equal_min_max() {
        let schema = json!({"type": "integer", "minimum": 5, "maximum": 5});
        let mut rng = seeded_rng();
        let result = generate(&schema, &mut rng).unwrap();
        assert_eq!(result, json!(5));
        generate_and_validate(&schema);
    }

    #[test]
    fn test_boolean_schema_true() {
        let schema = json!(true);
        let mut rng = seeded_rng();
        let result = generate(&schema, &mut rng);
        assert!(result.is_ok());
    }

    #[test]
    fn test_boolean_schema_false() {
        let schema = json!(false);
        let mut rng = seeded_rng();
        let result = generate(&schema, &mut rng);
        assert!(result.is_err());
    }

    // ── Integration (bulk validation) ──

    #[test]
    fn test_person_schema() {
        let schema = json!({
            "type": "object",
            "properties": {
                "name": {"type": "string", "minLength": 1, "maxLength": 50},
                "age": {"type": "integer", "minimum": 0, "maximum": 150},
                "address": {
                    "type": "object",
                    "properties": {
                        "street": {"type": "string"},
                        "city": {"type": "string"},
                        "zip": {"type": "string", "minLength": 5, "maxLength": 10}
                    },
                    "required": ["street", "city"]
                },
                "tags": {
                    "type": "array",
                    "items": {"type": "string"},
                    "minItems": 0,
                    "maxItems": 5
                }
            },
            "required": ["name", "age"]
        });
        generate_and_validate_n(&schema, 100);
    }

    #[test]
    fn test_product_schema() {
        let schema = json!({
            "type": "object",
            "properties": {
                "name": {"type": "string", "minLength": 1, "maxLength": 100},
                "price": {"type": "number", "minimum": 0.01, "maximum": 99999.99},
                "categories": {
                    "type": "array",
                    "items": {"type": "string"},
                    "minItems": 1,
                    "maxItems": 5
                },
                "inStock": {"type": "boolean"}
            },
            "required": ["name", "price", "categories", "inStock"]
        });
        generate_and_validate_n(&schema, 100);
    }

    // ── Format ──

    fn validate_with_formats(schema: &Value, instance: &Value) -> bool {
        jsonschema::options()
            .should_validate_formats(true)
            .build(schema)
            .expect("valid schema")
            .is_valid(instance)
    }

    #[test]
    fn test_string_format_date_time() {
        let schema = json!({"type": "string", "format": "date-time"});
        let mut rng = seeded_rng();
        for i in 0..100 {
            let result = generate(&schema, &mut rng).expect("generation should succeed");
            assert!(
                validate_with_formats(&schema, &result),
                "sample {i} does not validate as date-time.\nvalue: {result}"
            );
        }
    }

    #[test]
    fn test_string_format_date_time_structure() {
        let schema = json!({"type": "string", "format": "date-time"});
        let mut rng = seeded_rng();
        for _ in 0..100 {
            let result = generate(&schema, &mut rng).unwrap();
            let s = result.as_str().unwrap();
            // Expected format: YYYY-MM-DDThh:mm:ssZ
            assert!(s.ends_with('Z'), "should end with Z: {s}");
            let parts: Vec<&str> = s.trim_end_matches('Z').split('T').collect();
            assert_eq!(parts.len(), 2, "should have date and time parts: {s}");
            let date_parts: Vec<i32> = parts[0].split('-').map(|p| p.parse().unwrap()).collect();
            let time_parts: Vec<i32> = parts[1].split(':').map(|p| p.parse().unwrap()).collect();
            assert!(
                (1970..=2099).contains(&date_parts[0]),
                "year out of range: {s}"
            );
            assert!((1..=12).contains(&date_parts[1]), "month out of range: {s}");
            assert!((1..=31).contains(&date_parts[2]), "day out of range: {s}");
            assert!((0..=23).contains(&time_parts[0]), "hour out of range: {s}");
            assert!(
                (0..=59).contains(&time_parts[1]),
                "minute out of range: {s}"
            );
            assert!(
                (0..=59).contains(&time_parts[2]),
                "second out of range: {s}"
            );
        }
    }

    #[test]
    fn test_string_format_date_time_feb_leap_year() {
        let schema = json!({"type": "string", "format": "date-time"});
        let mut rng = seeded_rng();
        for _ in 0..2000 {
            let result = generate(&schema, &mut rng).unwrap();
            let s = result.as_str().unwrap();
            let parts: Vec<&str> = s.trim_end_matches('Z').split('T').collect();
            let date_parts: Vec<i32> = parts[0].split('-').map(|p| p.parse().unwrap()).collect();
            let year = date_parts[0];
            let month = date_parts[1];
            let day = date_parts[2];
            if month == 2 {
                let is_leap = (year % 4 == 0 && year % 100 != 0) || (year % 400 == 0);
                let max_day = if is_leap { 29 } else { 28 };
                assert!(
                    day <= max_day,
                    "Feb day {day} exceeds max {max_day} for year {year}: {s}"
                );
            }
        }
    }

    #[test]
    fn test_string_format_date() {
        let schema = json!({"type": "string", "format": "date"});
        let mut rng = seeded_rng();
        for i in 0..100 {
            let result = generate(&schema, &mut rng).expect("generation should succeed");
            assert!(
                validate_with_formats(&schema, &result),
                "sample {i} does not validate as date.\nvalue: {result}"
            );
        }
    }

    #[test]
    fn test_string_format_date_structure() {
        let schema = json!({"type": "string", "format": "date"});
        let mut rng = seeded_rng();
        for _ in 0..100 {
            let result = generate(&schema, &mut rng).unwrap();
            let s = result.as_str().unwrap();
            let parts: Vec<i32> = s.split('-').map(|p| p.parse().unwrap()).collect();
            assert_eq!(parts.len(), 3, "should have 3 date parts: {s}");
            assert!((1970..=2099).contains(&parts[0]), "year out of range: {s}");
            assert!((1..=12).contains(&parts[1]), "month out of range: {s}");
            assert!((1..=31).contains(&parts[2]), "day out of range: {s}");
        }
    }

    #[test]
    fn test_string_format_time() {
        let schema = json!({"type": "string", "format": "time"});
        let mut rng = seeded_rng();
        for i in 0..100 {
            let result = generate(&schema, &mut rng).expect("generation should succeed");
            assert!(
                validate_with_formats(&schema, &result),
                "sample {i} does not validate as time.\nvalue: {result}"
            );
        }
    }

    #[test]
    fn test_string_format_time_structure() {
        let schema = json!({"type": "string", "format": "time"});
        let mut rng = seeded_rng();
        for _ in 0..100 {
            let result = generate(&schema, &mut rng).unwrap();
            let s = result.as_str().unwrap();
            assert!(s.ends_with('Z'), "should end with Z: {s}");
            let parts: Vec<i32> = s
                .trim_end_matches('Z')
                .split(':')
                .map(|p| p.parse().unwrap())
                .collect();
            assert_eq!(parts.len(), 3, "should have 3 time parts: {s}");
            assert!((0..=23).contains(&parts[0]), "hour out of range: {s}");
            assert!((0..=59).contains(&parts[1]), "minute out of range: {s}");
            assert!((0..=59).contains(&parts[2]), "second out of range: {s}");
        }
    }

    #[test]
    fn test_string_format_duration() {
        let schema = json!({"type": "string", "format": "duration"});
        let mut rng = seeded_rng();
        let validator = jsonschema::options()
            .should_validate_formats(true)
            .with_draft(jsonschema::Draft::Draft201909)
            .build(&schema)
            .expect("valid schema");
        for i in 0..100 {
            let result = generate(&schema, &mut rng).expect("generation should succeed");
            assert!(
                validator.is_valid(&result),
                "sample {i} does not validate as duration.\nvalue: {result}"
            );
        }
    }

    #[test]
    fn test_string_format_duration_structure() {
        let schema = json!({"type": "string", "format": "duration"});
        let mut rng = seeded_rng();
        for _ in 0..100 {
            let result = generate(&schema, &mut rng).unwrap();
            let s = result.as_str().unwrap();
            assert!(s.starts_with('P'), "duration should start with P: {s}");
            assert!(s.len() > 1, "duration should have components after P: {s}");
        }
    }

    #[test]
    fn test_string_format_uuid() {
        let schema = json!({"type": "string", "format": "uuid"});
        let mut rng = seeded_rng();
        for i in 0..100 {
            let result = generate(&schema, &mut rng).expect("generation should succeed");
            assert!(
                validate_with_formats(&schema, &result),
                "sample {i} does not validate as uuid.\nvalue: {result}"
            );
        }
    }

    #[test]
    fn test_string_format_uuid_structure() {
        let schema = json!({"type": "string", "format": "uuid"});
        let mut rng = seeded_rng();
        for _ in 0..100 {
            let result = generate(&schema, &mut rng).unwrap();
            let s = result.as_str().unwrap();
            let groups: Vec<&str> = s.split('-').collect();
            assert_eq!(groups.len(), 5, "should have 5 groups: {s}");
            let lens: Vec<usize> = groups.iter().map(|g| g.len()).collect();
            assert_eq!(lens, [8, 4, 4, 4, 12], "group lengths: {s}");
            assert!(s.starts_with(|c: char| c.is_ascii_hexdigit()));
            assert_eq!(&groups[2][..1], "4", "should be version 4: {s}");
            assert!(
                "89ab".contains(&groups[3][..1]),
                "variant bits should be 10xx: {s}"
            );
        }
    }

    #[test]
    fn test_string_format_email() {
        let schema = json!({"type": "string", "format": "email"});
        let mut rng = seeded_rng();
        for i in 0..100 {
            let result = generate(&schema, &mut rng).expect("generation should succeed");
            assert!(
                validate_with_formats(&schema, &result),
                "sample {i} does not validate as email.\nvalue: {result}"
            );
        }
    }

    #[test]
    fn test_string_format_uri() {
        let schema = json!({"type": "string", "format": "uri"});
        let mut rng = seeded_rng();
        for i in 0..100 {
            let result = generate(&schema, &mut rng).expect("generation should succeed");
            assert!(
                validate_with_formats(&schema, &result),
                "sample {i} does not validate as uri.\nvalue: {result}"
            );
        }
    }

    #[test]
    fn test_string_format_hostname() {
        let schema = json!({"type": "string", "format": "hostname"});
        let mut rng = seeded_rng();
        for i in 0..100 {
            let result = generate(&schema, &mut rng).expect("generation should succeed");
            assert!(
                validate_with_formats(&schema, &result),
                "sample {i} does not validate as hostname.\nvalue: {result}"
            );
        }
    }

    #[test]
    fn test_string_format_ipv4() {
        let schema = json!({"type": "string", "format": "ipv4"});
        let mut rng = seeded_rng();
        for i in 0..100 {
            let result = generate(&schema, &mut rng).expect("generation should succeed");
            assert!(
                validate_with_formats(&schema, &result),
                "sample {i} does not validate as ipv4.\nvalue: {result}"
            );
        }
    }

    #[test]
    fn test_string_format_ipv6() {
        let schema = json!({"type": "string", "format": "ipv6"});
        let mut rng = seeded_rng();
        for i in 0..100 {
            let result = generate(&schema, &mut rng).expect("generation should succeed");
            assert!(
                validate_with_formats(&schema, &result),
                "sample {i} does not validate as ipv6.\nvalue: {result}"
            );
        }
    }

    #[test]
    fn test_string_format_unknown_falls_back() {
        let schema = json!({"type": "string", "format": "unknown-format"});
        let mut rng = seeded_rng();
        let result = generate(&schema, &mut rng);
        assert!(result.is_ok(), "unknown format should not error");
        assert!(result.unwrap().is_string());
    }

    #[test]
    fn test_string_format_date_time_ignores_length_constraints() {
        let schema =
            json!({"type": "string", "format": "date-time", "minLength": 1000, "maxLength": 2000});
        let mut rng = seeded_rng();
        let result = generate(&schema, &mut rng).expect("generation should succeed");
        let s = result.as_str().unwrap();
        // date-time format should take precedence, producing a ~20 char string
        assert!(
            s.len() < 100,
            "format should override length constraints, got len {}",
            s.len()
        );
        assert!(validate_with_formats(
            &json!({"type": "string", "format": "date-time"}),
            &result
        ));
    }

    // ── Pattern ──

    #[test]
    fn test_string_pattern_literal() {
        let schema = json!({"type": "string", "pattern": "^abc$"});
        generate_and_validate(&schema);
    }

    #[test]
    fn test_string_pattern_unanchored() {
        // A full match trivially satisfies `pattern`'s unanchored search.
        let schema = json!({"type": "string", "pattern": "foo"});
        generate_and_validate_n(&schema, 20);
    }

    #[test]
    fn test_string_pattern_date_like() {
        let schema = json!({"type": "string", "pattern": r"^\d{4}-\d{2}-\d{2}$"});
        generate_and_validate_n(&schema, 50);
    }

    #[test]
    fn test_string_pattern_alternation() {
        let schema = json!({"type": "string", "pattern": "^(red|green|blue)$"});
        generate_and_validate_n(&schema, 20);
    }

    #[test]
    fn test_string_pattern_char_class() {
        let schema = json!({"type": "string", "pattern": "^[a-f0-9]{8}$"});
        generate_and_validate_n(&schema, 20);
    }

    #[test]
    fn test_string_pattern_negated_class() {
        let schema = json!({"type": "string", "pattern": "^[^0-9]{3}$"});
        generate_and_validate_n(&schema, 20);
    }

    #[test]
    fn test_string_pattern_perl_classes() {
        let schema = json!({"type": "string", "pattern": r"^\w+\s\d+$"});
        generate_and_validate_n(&schema, 20);
    }

    #[test]
    fn test_string_pattern_case_insensitive() {
        let schema = json!({"type": "string", "pattern": "(?i)^abc$"});
        generate_and_validate_n(&schema, 20);
    }

    #[test]
    fn test_string_pattern_repetition_operators() {
        let schema = json!({"type": "string", "pattern": "^a+b*c?$"});
        generate_and_validate_n(&schema, 20);
    }

    #[test]
    fn test_string_pattern_bounded_repetition() {
        let schema = json!({"type": "string", "pattern": "^[ab]{2,5}$"});
        generate_and_validate_n(&schema, 20);
    }

    #[test]
    fn test_string_pattern_unicode_class() {
        let schema = json!({"type": "string", "pattern": r"^\p{L}{3}$"});
        generate_and_validate_n(&schema, 20);
    }

    #[test]
    fn test_string_pattern_beats_format() {
        let schema = json!({"type": "string", "pattern": r"^\d{3}$", "format": "date"});
        generate_and_validate(&schema);
        let mut rng = seeded_rng();
        let result = generate(&schema, &mut rng).expect("generation should succeed");
        let s = result.as_str().unwrap();
        assert_eq!(s.chars().count(), 3, "pattern should win over format: {s}");
        assert!(
            s.chars().all(|c| c.is_ascii_digit()),
            "pattern should win over format: {s}"
        );
    }

    #[test]
    fn test_string_pattern_with_max_length() {
        // BCP 47-ish: the unbounded `*` can generate far past maxLength, so
        // samples must be redrawn until one fits.
        let schema = json!({
            "type": "string",
            "pattern": "^[a-zA-Z]{2,3}(-[a-zA-Z0-9]{2,8})*$",
            "minLength": 2,
            "maxLength": 20
        });
        generate_and_validate_n(&schema, 200);
    }

    #[test]
    fn test_string_pattern_min_length_conflict_returns_error() {
        // Every match is exactly two chars; minLength 10 is unsatisfiable.
        let schema = json!({"type": "string", "pattern": "^ab$", "minLength": 10});
        let mut rng = seeded_rng();
        let err = generate(&schema, &mut rng).unwrap_err();
        assert!(
            matches!(err, crate::Error::ConflictingConstraints { .. }),
            "expected ConflictingConstraints, got: {err}"
        );
    }

    #[test]
    fn test_string_pattern_max_length_conflict_returns_error() {
        let schema = json!({"type": "string", "pattern": "^[a-z]{10}$", "maxLength": 5});
        let mut rng = seeded_rng();
        let err = generate(&schema, &mut rng).unwrap_err();
        assert!(
            matches!(err, crate::Error::ConflictingConstraints { .. }),
            "expected ConflictingConstraints, got: {err}"
        );
    }

    #[test]
    fn test_string_pattern_invalid_regex_falls_back() {
        // jsonschema cannot compile this schema, so no validation oracle;
        // generation should fall back to an unconstrained string.
        let schema = json!({"type": "string", "pattern": "(unclosed"});
        let mut rng = seeded_rng();
        let result = generate(&schema, &mut rng);
        assert!(result.is_ok(), "invalid pattern should not error");
        assert!(result.unwrap().is_string());
    }

    #[test]
    fn test_string_pattern_determinism() {
        let schema = json!({"type": "string", "pattern": r"^[a-z]{5}-\d{3}$"});
        let mut rng_a = seeded_rng();
        let mut rng_b = seeded_rng();
        let a = generate(&schema, &mut rng_a).expect("generation should succeed");
        let b = generate(&schema, &mut rng_b).expect("generation should succeed");
        assert_eq!(a, b);
    }

    // ── Integration (bulk validation) ──

    #[test]
    fn test_schema_with_refs() {
        let schema = json!({
            "$defs": {
                "Address": {
                    "type": "object",
                    "properties": {
                        "street": {"type": "string", "minLength": 1},
                        "city": {"type": "string", "minLength": 1},
                        "country": {"type": "string", "minLength": 1}
                    },
                    "required": ["street", "city", "country"]
                },
                "ContactInfo": {
                    "type": "object",
                    "properties": {
                        "email": {"type": "string"},
                        "phone": {"type": "string"}
                    },
                    "required": ["email"]
                }
            },
            "type": "object",
            "properties": {
                "name": {"type": "string", "minLength": 1, "maxLength": 50},
                "homeAddress": {"$ref": "#/$defs/Address"},
                "workAddress": {"$ref": "#/$defs/Address"},
                "contact": {"$ref": "#/$defs/ContactInfo"}
            },
            "required": ["name", "homeAddress", "contact"]
        });
        generate_and_validate_n(&schema, 100);
    }
}
